# Generated by Django 5.1.1 on 2025-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 10 mg/ml', max_length=100),
        ),
    ]
