# Generated by Django 5.1.1 on 2025-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
