# Generated by Django 5.1.1 on 2025-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicine_category_medicine_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
